imports:
    - { resource: db.yml }

parameters:
    # ...
    mailer.transport: sendmail
    env(USER): ALBERT

services:
    mailer:
        class:     Mailer
        public:    true 
        arguments: ['transport']

    newsletter_manager:
        class:     NewsletterManager
        calls:
            - [setMailer, ['@mailer', '%env(USER)%']]

        